using AspNetCoreMvc.Models;
using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace AspNetCoreMvc.Services
{
	public class AiSuggestionService
	{
		private static readonly JsonSerializerOptions JsonOptions = new JsonSerializerOptions
		{
			PropertyNamingPolicy = JsonNamingPolicy.CamelCase
		};

		private readonly AiSettingsStore _settingsStore;
		private readonly HttpClient _httpClient;

		public AiSuggestionService(AiSettingsStore settingsStore, HttpClient httpClient)
		{
			_settingsStore = settingsStore;
			_httpClient = httpClient;
		}

		public async Task<AiGeneratedSuggestion> GenerateAsync(AiSuggestionRunRequest request)
		{
			var settings = await _settingsStore.GetStoredSettingsAsync();
			var normalizedAction = NormalizeAction(request?.Action);

			if (string.Equals(settings.Mode, "openai-compatible", StringComparison.Ordinal))
			{
				return await GenerateOpenAiCompatibleSuggestionAsync(settings, request, normalizedAction);
			}

			return GenerateDemoSuggestion(request, normalizedAction);
		}

		private static AiGeneratedSuggestion GenerateDemoSuggestion(AiSuggestionRunRequest request, string action)
		{
			var selection = NormalizeText(request?.AnchorText);
			var tone = NormalizeTone(request?.Tone);
			var instruction = NormalizeText(request?.Instruction);
			var currentDocumentText = ExtractPlainText(request.Document);
			var revised = action switch
			{
				"proofread" => ProofreadText(selection),
				"shorten" => ShortenText(selection),
				"expand" => ExpandText(selection, currentDocumentText),
				"summarize" => SummarizeText(selection),
				_ => RewriteText(selection, tone)
			};

			if (!string.IsNullOrWhiteSpace(instruction))
			{
				revised = ApplyInstructionHint(revised, instruction, action);
			}

			if (string.Equals(revised, selection, StringComparison.Ordinal))
			{
				revised = ProofreadText(selection);
			}

			return new AiGeneratedSuggestion
			{
				Action = action,
				Mode = "demo",
				Provider = "demo-local",
				SuggestionType = "format",
				SuggestedText = revised,
				Body = BuildDemoReviewerNote(action, tone, instruction),
				Message = "Created a demo AI " + action + " suggestion for the current selection."
			};
		}

		private async Task<AiGeneratedSuggestion> GenerateOpenAiCompatibleSuggestionAsync(
			AiProviderSettingsSnapshot settings,
			AiSuggestionRunRequest request,
			string action)
		{
			if (string.IsNullOrWhiteSpace(settings.ApiKey))
			{
				throw new InvalidOperationException("OpenAI-compatible mode requires an admin API key.");
			}

			var selection = NormalizeText(request?.AnchorText);
			var tone = NormalizeTone(request?.Tone);
			var documentText = ExtractPlainText(request.Document);
			var prompt = BuildOpenAiPrompt(selection, documentText, action, tone, request?.Instruction);
			var endpoint = settings.ApiBaseUrl.TrimEnd('/') + "/v1/chat/completions";

			using var requestMessage = new HttpRequestMessage(HttpMethod.Post, endpoint);
			requestMessage.Headers.Authorization = new AuthenticationHeaderValue("Bearer", settings.ApiKey);
			requestMessage.Content = new StringContent(
				JsonSerializer.Serialize(new
				{
					model = settings.Model,
					temperature = settings.Temperature,
					messages = new object[]
					{
						new { role = "system", content = settings.SystemPrompt },
						new { role = "user", content = prompt }
					}
				}, JsonOptions),
				Encoding.UTF8,
				"application/json");

			using var response = await _httpClient.SendAsync(requestMessage);
			var responseText = await response.Content.ReadAsStringAsync();
			if (!response.IsSuccessStatusCode)
			{
				throw new InvalidOperationException("AI provider request failed: " + ExtractErrorMessage(responseText, response.ReasonPhrase));
			}

			var suggestedText = ExtractChatCompletionText(responseText);
			if (string.IsNullOrWhiteSpace(suggestedText))
			{
				throw new InvalidOperationException("AI provider returned an empty suggestion.");
			}

			return new AiGeneratedSuggestion
			{
				Action = action,
				Mode = "openai-compatible",
				Provider = settings.Model,
				SuggestionType = "format",
				SuggestedText = suggestedText.Trim(),
				Body = "AI " + action + " suggestion generated by " + settings.Model + ".",
				Message = "Created an AI " + action + " suggestion using " + settings.Model + "."
			};
		}

		private static string BuildOpenAiPrompt(string selection, string documentText, string action, string tone, string instruction)
		{
			var builder = new StringBuilder();
			builder.AppendLine("Revise the selected editor text.");
			builder.AppendLine("Action: " + action);
			builder.AppendLine("Tone: " + tone);
			if (!string.IsNullOrWhiteSpace(instruction))
			{
				builder.AppendLine("Additional instruction: " + instruction.Trim());
			}

			if (!string.IsNullOrWhiteSpace(documentText))
			{
				builder.AppendLine();
				builder.AppendLine("Document context:");
				builder.AppendLine(documentText.Length > 1500 ? documentText.Substring(0, 1500) : documentText);
			}

			builder.AppendLine();
			builder.AppendLine("Selected text:");
			builder.AppendLine(selection);
			builder.AppendLine();
			builder.AppendLine("Return only the revised replacement text. Do not include markdown fences, labels, or explanations.");
			return builder.ToString();
		}

		private static string ExtractChatCompletionText(string json)
		{
			using var document = JsonDocument.Parse(json);
			if (!document.RootElement.TryGetProperty("choices", out var choices) || choices.ValueKind != JsonValueKind.Array || choices.GetArrayLength() == 0)
			{
				return string.Empty;
			}

			var message = choices[0].GetProperty("message");
			if (message.TryGetProperty("content", out var content))
			{
				return content.GetString() ?? string.Empty;
			}

			return string.Empty;
		}

		private static string ExtractErrorMessage(string json, string fallback)
		{
			try
			{
				using var document = JsonDocument.Parse(json);
				if (document.RootElement.TryGetProperty("error", out var error) &&
					error.TryGetProperty("message", out var message))
				{
					return message.GetString() ?? fallback ?? "Unknown provider error.";
				}
			}
			catch (JsonException)
			{
			}

			return string.IsNullOrWhiteSpace(json) ? (fallback ?? "Unknown provider error.") : json;
		}

		private static string RewriteText(string value, string tone)
		{
			var revised = ProofreadText(value)
				.Replace("utilize", "use", StringComparison.OrdinalIgnoreCase)
				.Replace("in order to", "to", StringComparison.OrdinalIgnoreCase)
				.Replace("at this point in time", "now", StringComparison.OrdinalIgnoreCase)
				.Replace(" in the event that ", " if ", StringComparison.OrdinalIgnoreCase);

			if (string.Equals(tone, "friendly", StringComparison.Ordinal))
			{
				revised = revised.Replace("Please", "Please", StringComparison.Ordinal)
					.Replace("We recommend", "A good next step is", StringComparison.OrdinalIgnoreCase);
			}
			else if (string.Equals(tone, "concise", StringComparison.Ordinal))
			{
				revised = ShortenText(revised);
			}

			return revised;
		}

		private static string ProofreadText(string value)
		{
			var revised = NormalizeText(value);
			revised = Regex.Replace(revised, "\\s+([,.;:!?])", "$1");
			revised = Regex.Replace(revised, "([,.;:!?])(\\S)", "$1 $2");
			if (!string.IsNullOrWhiteSpace(revised))
			{
				revised = char.ToUpperInvariant(revised[0]) + revised.Substring(1);
			}

			if (!revised.EndsWith(".") && !revised.EndsWith("!") && !revised.EndsWith("?"))
			{
				revised += ".";
			}

			return revised;
		}

		private static string ShortenText(string value)
		{
			var revised = NormalizeText(value);
			revised = Regex.Replace(revised, "\\b(really|very|just|quite|actually|basically|clearly)\\b\\s*", string.Empty, RegexOptions.IgnoreCase);
			revised = revised
				.Replace(" in order to ", " to ", StringComparison.OrdinalIgnoreCase)
				.Replace(" in the event that ", " if ", StringComparison.OrdinalIgnoreCase)
				.Replace(" due to the fact that ", " because ", StringComparison.OrdinalIgnoreCase);
			revised = Regex.Replace(revised, "\\s{2,}", " ");
			return ProofreadText(revised);
		}

		private static string ExpandText(string value, string documentText)
		{
			var revised = ProofreadText(value);
			if (!string.IsNullOrWhiteSpace(documentText) &&
				documentText.IndexOf("review", StringComparison.OrdinalIgnoreCase) >= 0)
			{
				return revised + " This version also makes the review intent and next step more explicit.";
			}

			return revised + " This version adds a bit more context so the next step is clearer for the reader.";
		}

		private static string SummarizeText(string value)
		{
			var revised = NormalizeText(value);
			var sentences = Regex.Split(revised, "(?<=[.!?])\\s+");
			if (sentences.Length > 1)
			{
				revised = sentences[0];
			}

			if (revised.Length > 140)
			{
				revised = revised.Substring(0, 137).TrimEnd() + "...";
			}

			return ProofreadText(revised);
		}

		private static string ApplyInstructionHint(string revised, string instruction, string action)
		{
			if (instruction.IndexOf("bullet", StringComparison.OrdinalIgnoreCase) >= 0 && action == "summarize")
			{
				return "- " + revised.Trim();
			}

			if (instruction.IndexOf("formal", StringComparison.OrdinalIgnoreCase) >= 0)
			{
				return revised.Replace("A good next step is", "We recommend", StringComparison.OrdinalIgnoreCase);
			}

			return revised;
		}

		private static string BuildDemoReviewerNote(string action, string tone, string instruction)
		{
			var note = "Demo AI " + action + " suggestion";
			if (!string.IsNullOrWhiteSpace(tone))
			{
				note += " in a " + tone + " tone";
			}

			if (!string.IsNullOrWhiteSpace(instruction))
			{
				note += ". Instruction: " + instruction.Trim();
			}

			return note + ".";
		}

		private static string ExtractPlainText(JsonElement document)
		{
			if (document.ValueKind != JsonValueKind.Object)
			{
				return string.Empty;
			}

			var builder = new StringBuilder();
			AppendNodeText(document, builder);
			var normalized = Regex.Replace(builder.ToString(), "\\n{3,}", "\n\n");
			return normalized.Trim();
		}

		private static void AppendNodeText(JsonElement node, StringBuilder builder)
		{
			if (node.ValueKind == JsonValueKind.Array)
			{
				foreach (var item in node.EnumerateArray())
				{
					AppendNodeText(item, builder);
				}

				return;
			}

			if (node.ValueKind != JsonValueKind.Object)
			{
				return;
			}

			var type = node.TryGetProperty("type", out var typeProperty)
				? typeProperty.GetString()
				: string.Empty;

			if (string.Equals(type, "text", StringComparison.Ordinal))
			{
				if (node.TryGetProperty("text", out var textProperty))
				{
					builder.Append(textProperty.GetString());
				}

				return;
			}

			if (string.Equals(type, "hardBreak", StringComparison.Ordinal))
			{
				builder.AppendLine();
				return;
			}

			if (node.TryGetProperty("content", out var content))
			{
				AppendNodeText(content, builder);
			}

			if (IsBlockNode(type))
			{
				builder.AppendLine();
			}
		}

		private static bool IsBlockNode(string type)
		{
			return string.Equals(type, "paragraph", StringComparison.Ordinal) ||
				string.Equals(type, "heading", StringComparison.Ordinal) ||
				string.Equals(type, "bulletList", StringComparison.Ordinal) ||
				string.Equals(type, "orderedList", StringComparison.Ordinal) ||
				string.Equals(type, "listItem", StringComparison.Ordinal) ||
				string.Equals(type, "codeBlock", StringComparison.Ordinal) ||
				string.Equals(type, "blockquote", StringComparison.Ordinal);
		}

		private static string NormalizeAction(string value)
		{
			if (string.IsNullOrWhiteSpace(value))
			{
				return "rewrite";
			}

			var normalized = value.Trim().ToLowerInvariant();
			return normalized switch
			{
				"proofread" => "proofread",
				"rewrite" => "rewrite",
				"shorten" => "shorten",
				"expand" => "expand",
				"summarize" => "summarize",
				_ => "rewrite"
			};
		}

		private static string NormalizeTone(string value)
		{
			if (string.IsNullOrWhiteSpace(value))
			{
				return "professional";
			}

			return value.Trim().ToLowerInvariant();
		}

		private static string NormalizeText(string value)
		{
			if (string.IsNullOrWhiteSpace(value))
			{
				return string.Empty;
			}

			return Regex.Replace(value.Trim(), "\\s+", " ");
		}

		public class AiGeneratedSuggestion
		{
			public string Action { get; set; }
			public string Mode { get; set; }
			public string Provider { get; set; }
			public string SuggestionType { get; set; }
			public string SuggestedText { get; set; }
			public string Body { get; set; }
			public string Message { get; set; }
		}
	}
}
